services:
  bot:
    container_name: telegram-bot
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: reminder_bot
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: